### ISSUE TITLE
複数JSON対応

### ISSUE THREAD

**Issue by takumaki** [ntechlab/calendar#5]
複数のevents.jsonファイルを受け付けるようにするか、
それとも複数のjsonファイルをもとにevents.jsonファイルを生成するバッチを作るか、、どっちがいいのかな？
後者のほうが楽？

**Comment by tnog2014** [comment]
所定のフォルダ内のjsonファイルをすべて読み込むようにするのでどうでしょう？
そうすると、カレンダー情報の追加・削除がファイルの追加・削除だけで簡単にできます。
