### ISSUE TITLE
イベントの詳細情報

### ISSUE THREAD

**Issue by takumaki** [ntechlab/calendar#7]
現状の機能だとイベントのタイトルしか扱えないっぽい？
そもそもjsonにそんな項目はなさそうだし。
でも、あったほうが便利。

**Comment by tnog2014** [comment]
calendarのAPIドキュメントによると、JSONデータに自由に項目を追加してよいとのことです。オプション情報として、いろいろなデータを持てます。

**Comment by takumaki** [comment]
ありがとうございます。
jsonに説明文の項目を追加して、アラートで表示するだけの対応は入れてみました。
